# File: config/email.yml
# This is a very strict format. Please use : before options, except environment
# if tls is needed with ruby < 1.8.7, check out action_mailer_optional_tls plugin.
# using ruby < 1.8.7 will add aditional problems with reading email configuration from YAML.
production:
    :tls: "true"
    #:enable_starttls_auto: true
    :address: "smtp.gmail.com"
    :port: '587'
    :domain: "smtp.gmail.com"
    :authentication: :plain
    :user_name: "zomg.sandbox@gmail.com"
    :password: "zomg1234"

development:
    :tls: "true"
    #:enable_starttls_auto: true
    :address: "smtp.gmail.com"
    :port: '587'
    :domain: "smtp.gmail.com"
    :authentication: :plain
    :user_name: "zomg.sandbox@gmail.com"
    :password: "zomg1234"

